services:
  gameserver:
    image: ghcr.io/melkortf/tf2-base:latest
    environment:
      - "SERVER_HOSTNAME=test-server"
      - "PORT=27015"
      - "CLIENT_PORT=27016"
      - "STEAM_PORT=27017"
      - "STV_PORT=27020"
      - "RCON_PASSWORD=password"
    network_mode: host
    stdin_open: true
    tty: true