/// <reference types="@types/node" />
import { createSocket, type RemoteInfo, type Socket } from "node:dgram";
import { parsePacket } from "./parser.ts";
import type { EventData, LogReceiverOptions } from "./types.ts";

/**
 * An event emitter that will emit a message event when a valid UDP log is created on the server
 *
 * When a log is sent, there will be a `message` event published that you can extract the data from. This is a valid payload. It is important to check the IP or password of the content to ensure it came from a trusted source
 *
 * You can listen on socket events such as `error` and `close` by listening to those events. All default events of the {@link Socket} will be forwarded. If you need to close the socket at any time, provide an {@link AbortSignal}. Aborting will automatically call {@link Socket.close} for you on the socket and emits a `close` event
 *
 * @example Simple receiver that logs to console every message
 * ```ts
 * import { LogReceiver } from "@c43721/srcds-log-receiver";
 *
 * const receiver = new LogReceiver({
 *   address: "0.0.0.0",
 *   port: 9871,
 * });
 *
 * await receiver.start();
 *
 * for await (const message of receiver) {
 *   console.log(message)
 * }
 * ```
 *
 * On every log generated by the srcds server, it will log that message out to console
 *
 * @example Passing in an abort controller to close the socket
 * ```ts
 * import { LogReceiver } from "@c43721/srcds-log-receiver";
 *
 * const controller = new AbortController();
 * const { signal } = controller;
 *
 * const receiver = new LogReceiver({
 *   address: "0.0.0.0",
 *   port: 9871,
 * });
 *
 * await receiver.start();
 *
 * // timeout after 5 seconds
 * setTimeout(() => {
 *   console.log("Aborting");
 *   controller.abort();
 * }, 5000);
 *
 * for await (const message of receiver) {
 *   console.log(message)
 * }
 *
 * ```
 *
 * While not required, there may be times where you have short-lived receivers. Since each instance creates a socket, closing those sockets becomes a problem. Abort controllers help with that by providing a way to explicitly close the resources for you
 *
 * @example Using the password and IP to verify the source of the data
 * ```ts
 * import { LogReceiver } from "@c43721/srcds-log-receiver";
 *
 * const receiver = new LogReceiver({
 *   address: "0.0.0.0",
 *   port: 9871,
 * });
 *
 * await receiver.start();
 *
 * for await (const data of receiver) {
 *   if (data.password === null) {
 *     console.log("Bad password");
 *   } else if (data.password === "mysuperdupersecret") {
 *     console.log(data);
 *   }
 * }
 *
 * ```
 *
 * For security reasons, you should always use a log secret to prevent evaluation of potentially malicious messages. Do this by looking at the password field. In order to set up the log secret, you can use the `sv_logsecret` command
 */
export class LogReceiver implements Disposable {
  #options: LogReceiverOptions;
  #socket: Socket | null = null;
  #stream: ReadableStream<EventData> | null = null;
  #listening: Promise<void> | null = null;

  /**
   * Creates a new receiver
   * @param options The log reciever options to use
   */
  constructor(options: LogReceiverOptions) {
    this.#options = options;
  }

  /*
   * Starts the log receiver
   *
   * This returns a promise which, when resolved, indicates the socket is listening. This method is safe to call multiple times.
   */
  async start(): Promise<void> {
    if (this.#socket) {
      return;
    }

    const { address, port, signal } = this.#options;
    const socket = createSocket({ type: "udp4", signal });

    this.#socket = socket;

    signal?.addEventListener("abort", () => this.close(), { once: true });

    this.#listening = new Promise((resolve, reject) => {
      const onListening = () => {
        socket.off("error", onError);
        resolve();
      };
      const onError = (error: Error) => {
        socket.off("listening", onListening);
        reject(error);
      };
      socket.once("listening", onListening);
      socket.once("error", onError);
    });

    socket.bind(port, address);

    this.#stream = new ReadableStream<EventData>({
      start: (controller) => {
        socket.on("message", (buffer: Uint8Array, info: RemoteInfo) => {
          const data = this.#handleMessage(buffer, info);

          if (data !== null) {
            controller.enqueue(data);
          }
        });

        socket.once("close", () => controller.close());
        socket.on("error", (err) => controller.error(err));
      },
      cancel: () => this.close(),
    });

    return await this.#listening;
  }

  /*
   * Gets the socket that the connection lives onListening
   */
  get socket(): Socket | null {
    return this.#socket;
  }

  /**
   * Destroys the socket
   */
  [Symbol.dispose]() {
    this.close();
  }

  /**
   * Closes the socket and stops listening for messages
   */
  close() {
    this.#socket?.close();
  }

  /**
   * Iterates over all the messages as they come in from the server
   */
  [Symbol.asyncIterator](): AsyncIterator<EventData> {
    if (!this.#socket) {
      throw new Error("Socket is not listening");
    }

    return this.#stream!.values();
  }

  #handleMessage(buffer: Uint8Array, serverInfo: RemoteInfo) {
    const response = parsePacket(buffer);

    if (response === null) {
      return null;
    }

    const eventData = { ...response, socket: serverInfo } satisfies EventData;

    return eventData;
  }
}
